const MOVIES = {
  LOAD: "LOAD_MOVIE",
  LOAD_SUCCESS: "SUCCESS_MOVIE",
  LOAD_FAIL: "FAIL_MOVIE",

  GENRE_LOAD: "GENRELOAD_MOVIE",
  GENRE_SUCCESS: "GENRESUCCESS_MOVIE",

  REC_LOAD: "RECLOAD_MOVIE",
  REC_LOAD_SUCCESS: "RECLOADSUCCESS_MOVIE",

  SEARCH_LOAD: "SLOAD_MOVIE",
  SEARCH_SUCCESS: "SSUCCESS_MOVIE",

  GETAMOVIE: "MLOAD_MOVIE",
  SETAMOVIE: "MSUCCESS_MOVIE",
  AMOVIE_FAIL: "MFAIL_MOVIE",

  CLEAR: "CLEAR_STATE_MOVIE",
};

const TV = {
  LOAD: "LOAD_TV",
  LOAD_SUCCESS: "SUCCESS_TV",
  LOAD_FAIL: "FAIL_TV",

  GENRE_LOAD: "GENRELOAD_TV",
  GENRE_SUCCESS: "GENRESUCCESS_TV",

  REC_LOAD: "RECLOAD_TV",
  REC_LOAD_SUCCESS: "RECLOADSUCCESS_TV",

  SEARCH_LOAD: "SLOAD_TV",
  SEARCH_SUCCESS: "SSUCCESS_TV",

  GETATV: "MLOAD_TV",
  SETATV: "MSUCCESS_TV",
  ATV_FAIL: "MFAIL_TV",

  CLEAR: "CLEAR_STATE_TV",
};

const navbarType = {
  HOME: "HOME",
  DASHBOARD: "DASHBOARD",
}

const cardType = {
  SUGGEST: "SUGGEST",
  SUGGESTION: "SUGGESTION",
  ADD: "ADD",
  ALREADY_WATCHED: "ALREADY_WATCHED",
  DEFAULT: "DEFAULT",
};

const MY_SECRET_KEY = "MY_MOVIE_DB_SECRET_KEY_225121";
export { MOVIES, navbarType, TV, cardType, MY_SECRET_KEY };
